create schema "ROOT";

CREATE TABLE IDENTITIES
    (IDENTITY_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    DISPLAY_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    UID VARCHAR(255) UNIQUE
    );

SELECT * from IDENTITIES

INSERT INTO IDENTITIES( DISPLAY_NAME, EMAIL, UID) values ('hai','abc@acb','aaa')

DROP table IDENTITIES;
